/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fcf8f8',
        'on-background': '#1c1b1b',
        surface: '#fcf8f8',
        'on-surface': '#1c1b1b',
        'surface-dim': '#ddd9d9',
        'surface-bright': '#fcf8f8',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#444748',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        primary: '#5d5f5f',
        'on-primary': '#ffffff',
        'primary-container': '#ffffff',
        'on-primary-container': '#747676',
        secondary: '#2b5daa',
        'on-secondary': '#ffffff',
        'secondary-container': '#7fabfe',
        'on-secondary-container': '#003d83',
        'secondary-fixed': '#d7e2ff',
        'on-secondary-fixed': '#001a40',
        tertiary: '#635d5e',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        outline: '#747878',
        'outline-variant': '#c4c7c8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Geist', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      spacing: {
        base: '8px',
        gutter: '16px',
        margin: '24px',
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
